version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: paylink
      POSTGRES_PASSWORD: password
      POSTGRES_DB: paylink
    ports:
      - "5432:5432"
  redis:
    image: redis:7
    ports:
      - "6379:6379"
